import './globals.css'
import type { Metadata } from 'next'
import { Inter, Montserrat, Inconsolata, Poppins } from "next/font/google";

// Font imports
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  preload: true
});

const poppins = Poppins({
  subsets: ['latin-ext'],
  variable: '--font-poppins',
  preload: true,
  weight: '400'
});

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  preload: true
});

const inconsolata = Inconsolata({
  subsets: ['latin'],
  variable: '--font-inconsolata',
  preload: true
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${montserrat.variable} ${poppins.variable} ${inconsolata.variable}`}>{children}</body>
    </html>
  )
}
